### ISSUE TITLE
TimedOut Deadline expired

### ISSUE THREAD

**Issue by benbaptist** [oSumAtrIX/DownOnSpot#66] opened 2023-10-13 18:12 UTC
**Describe the bug**
Many tracks intermittently fail to download, while downloading a playlist, with the following error:
```
IO: TimedOut Deadline expired before operation could complete { wait timeout exceeded }
```

I've been experiencing this issue since I started using this tool in August. The only thing I can do is set my concurrent downloads to 1, which does not elminiate the issue, but helps it, and just keep running the script until all downloads have finished.

**To Reproduce**

1. Set consecutive downloads to either 1 or more - works better with just one, but still has issues - anything more than 1 concurrent download will almost always time out on every download
2. Execute `down_on_spot [playlist URL]`
3. Watch, as some tracks download successfully, and others fail

I tested this both on my Linux server and my macOS Ventura M2 laptop with the exact same outcome. 

**Expected behavior**
The tracks download successfully. 

**Desktop:**

- OS: macOS Ventura on Apple M2, AND Ubuntu Server Linux x86 on my server

**Comment by oSumAtrIX** [comment] 2023-10-14 03:25
Likely dupe of https://github.com/oSumAtrIX/DownOnSpot/issues/64

**Closed by oSumAtrIX** 2023-10-14 03:25 UTC

**Comment by benbaptist** [comment] 2023-10-20 17:36
I'm not quite certain it's the exact same issue, although I could be mistaken. It never freezes for me - it just simply fails quickly with a TimeOut, even though it doesn't wait for more than a few seconds. Unfortunately, I'm unfamiliar with the subject matter enough to provide much more insight. Is there any hidden verbose mode I could activate to help debug?

**Comment by oSumAtrIX** [comment] 2023-10-21 11:55
Maybe #64 referred to the same issue, but I'll reopen this one, as https://github.com/oSumAtrIX/DownOnSpot/tree/rewrite should solve it when ready.
