### ISSUE TITLE
Spotify Error: invalid_client after successfully authentication

### ISSUE THREAD

**Issue by fze015** [oSumAtrIX/DownOnSpot#104] opened 2024-08-28 11:29 UTC
**Describe the bug**
I can't downloading any songs after successfully authentification

**To Reproduce**

1. Generate _credentials.json_ file with [librespot-auth](https://github.com/dspearson/librespot-auth)
2. Move _credentials.json_ file to **credentials_cache** DownOnSpot folder
3. Download any songs with down_on_spot executable

**Expected behavior**
Playlist songs downloading

**Screenshots**
![Error](https://github.com/user-attachments/assets/dcc24f6a-4a64-4a02-8bf8-af88c98567e1)

**Desktop (please complete the following information):**

- OS: Debian

**Additional context**
I've tried to generate a credentials.json file with another account but i have the same error

#100

**Comment by oSumAtrIX** [comment] 2024-08-28 21:22
This is caused by librespot. Moving to #93

**Closed by oSumAtrIX** 2024-08-28 21:22 UTC

**Comment by fze015** [comment] 2024-08-28 22:42
But the problem of the mentioned issue is authentication, here authentication works fine

**Comment by oSumAtrIX** [comment] 2024-08-28 22:49
The error originates from login and is connected to #93
