### ISSUE TITLE
Error when downloading tracks - Error: Invalid state { BadDER } | <trackname>

### ISSUE THREAD

**Issue by ncc-hyperion** [oSumAtrIX/DownOnSpot#57] opened 2023-08-04 21:35 UTC
I've successfully compiled and ran on my mac, and successfully download an album (all be it with some tracks truncated/cut short)  I then tried another album

I'm now getting the following error when downloading

Error: Invalid state { BadDER } | <trackname>
Finished download(s) in xx second(s).

**Comment by ncc-hyperion** [comment] 2023-08-04 21:38
turns out that running the command using sudo makes it works. Apologies, I'm a command line novice.

**Comment by migo1271** [comment] 2023-08-05 15:35
I just recovered the shortened downloads, too. It appeared with downloads after I updated to version 0.2.4. Older version 0.2.3 seems still working. On 0.2.4, reducing the "concurrent_downloads" from 4 to 1 seems to solve the problem.

**Comment by ncc-hyperion** [comment] 2023-08-06 07:13
> I just recovered the shortened downloads, too. It appeared with downloads after I updated to version 0.2.4. Older version 0.2.3 seems still working. On 0.2.4, reducing the "concurrent_downloads" from 4 to 1 seems to solve the problem.

Yes, I updated my concurrent_downloads to 1 too, takes longer, but its at least reliable.

**Comment by Laiteux** [comment] 2023-08-15 23:28
Confirming this.

**Comment by oSumAtrIX** [comment] 2023-08-16 06:35
The application is currently fully rewritten in higher quality. Locally these bugs are fixed. Currently, I am working on returning all features, such as downloading playlists, concurrency, etc. Downloading single tracks works already.

**Comment by Laiteux** [comment] 2023-08-16 12:13
That's very nice to hear! Pretty excited, would you have an ETA on this? Or if the "main feature" already works, couldn't you make it a branch?

**Comment by ncc-hyperion** [comment] 2023-08-16 19:01
awesome news. I've been able to get around the issue with truncated tracks by running the command in multiple terminal windows in macOS.

This amazing tool has allowed me to replace some of my lower bitrate tracks.

**Comment by oSumAtrIX** [comment] 2023-08-16 23:42
@Laiteux I have pushed it: https://github.com/oSumAtrIX/DownOnSpot/tree/rewrite

Done: Download .ogg tracks
Todo: Convert to mp3 (broken, probably easy fix), tagging, parallelization, handling different types of inputs (playlists, albums, artists...)

**Comment by oSumAtrIX** [comment] 2023-08-18 13:52
Yes, there's a couple things left to do and bugs like this would be resorted on the way along

**Comment by Laiteux** [comment] 2023-08-18 18:43
Any idea about why the login cache isn't working by any chance? I've looked into the code but can't seem to figure it out

**Comment by oSumAtrIX** [comment] 2023-08-19 13:35
I am not sure...both clients use a cache and I do not get login notifications:

https://github.com/oSumAtrIX/DownOnSpot/blob/rewrite/src/spotify.rs#L29-L35
https://github.com/oSumAtrIX/DownOnSpot/blob/rewrite/src/download.rs#L52-L54

**Comment by oSumAtrIX** [comment] 2023-08-19 13:36
Maybe it is this: https://github.com/oSumAtrIX/DownOnSpot/blob/rewrite/src/spotify.rs#L39

Though we are getting very offtopic now, this may be moved to a separate issue.

**Comment by Laiteux** [comment] 2023-08-24 03:47
Gave it a quick look myself but didn't figure it out. Not a Rust dev. Do you think you could please have a look into this login cache issue yourself? Let me know if you'd want me to open a new issue, tho

**Comment by oSumAtrIX** [comment] 2023-09-07 22:43
I do this project on best effort basis. Once I have time I can look into it, shouldn't be too long.

**Comment by Laiteux** [comment] 2023-09-27 23:47
Seems like this was fixed by https://github.com/librespot-org/librespot/pull/1187

**Comment by oSumAtrIX** [comment] 2023-09-28 02:10
What could be the reason for my not being able to reproduce the issue?

**Comment by Laiteux** [comment] 2023-09-28 02:11
@oSumAtrIX check if your `credentials_cache/credentials.json` `auth_token` refreshes everytime you `run` - if so, you're getting reconnected everytime.

**Comment by Laiteux** [comment] 2023-09-28 03:45
https://github.com/librespot-org/librespot/pull/1206

**Comment by oSumAtrIX** [comment] 2023-11-26 01:26
Should be solved with 388736973582149a33c214f3634bb79644b13736.

**Closed by oSumAtrIX** 2023-11-26 01:26 UTC
Labels: Bug report
