### ISSUE TITLE
Stuck downloads do not time out

### ISSUE THREAD

**Issue by Brekkjern** [oSumAtrIX/DownOnSpot#82] opened 2024-05-05 13:41 UTC
**Describe the bug**
Sometimes downloads of songs will get stuck and they do not time out. Stopping the program will leave an unfinished file in place, and the subsequent runs of the program won't overwrite those files with the correct data. Deleting the file and running again will normally download the file correctly.

**To Reproduce**
Download a large playlist and a download might stall at some point. I have found no pattern to which tracks have this issue.

**Expected behavior**
Time out the download, delete the downloaded data, and either try again, or just skip the song.

**Screenshots**
![image](https://github.com/oSumAtrIX/DownOnSpot/assets/599405/739482b4-9553-4eb6-8356-2fcdf2e8aac4)

**Desktop (please complete the following information):**

- OS: Debian 12 on WSL Windows 11.
- librespot = "0.4.2"

**Additional context**

**Comment by oSumAtrIX** [comment] 2024-05-06 19:29
Dupe of https://github.com/oSumAtrIX/DownOnSpot/issues/64

**Closed by oSumAtrIX** 2024-05-06 19:29 UTC
